travis:
  secure:
    BINSTAR_TOKEN: qesNimhWuB6euCyh9HRrDpvLpRYdjo71GC2U2D2wWBivrmi81P+r43tB9vl6k7iqr/NQajqsDegbzkUPGzQiz+S82ZNxXqhSl4YhGnUgH1EMozv7lDyMGgzQ5D5twQAM2MfpJuMmBopMydqyReMT91AbuAti0FkImfYIaRMtw3Dslf0AKZXSg2DzwDoHKJqKf7tr6TtEpzvkXfUyGXkw+wT+k+5m+gHk4tRu3Pimsm81lRGfkvzYh4CQdJRt+3EsQY26ll5li3rK3fEkpWkfl9IF4Wny0N/gd4FAk8Sjt4tvtzQ/dhv0rlpFfxYrWEsL20tX3/8IKIhbtjtSM/FcS2GO2HouUQKODuPWgOjYIkh0R6PU9LlCDGHgJq8uzKTJijdNSHCyLKX3icci0+osKswyK2DYCAypG7Alus9jh4g9moABPkqEzYB9ZV0tXcLf4HbyxrZHLlYDmSKn0ynMl0NLFVOljOqfiRFkZLBrPJ3mlX+S4aRfNpldJXJe8LX77pW+JZs8aeKO5i1GEx5zvLV7CLlIRR7w3bQfV+bSRwofA32u45/9eJe1a+Ct/aTT+01JstGWmhrz7mHfPMh6NWtxHNi/TyLpqxeb4VC2JJtlbLpHdPGou0kNu36AXD4Uc/O9PHEOcmt1TEnr0wUfk7Q6whzOkwQz2nuqyUH/+2Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
